version: "2"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: unless-stopped
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=databasedb
      - MYSQL_USER=student1
    ports:
      - 3306:3306